name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore Dialogative.sln
    - name: Build
      run: dotnet build Dialogative.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test Dialogative.sln --configuration Release --no-build --verbosity normal

    - name: Pack with dotnet
      run: dotnet pack Dialogative/Dialogative.csproj --configuration Release --no-build -o ./artifacts


    - name: Push to Github Packages
      if: github.event_name == 'push'
      run: dotnet nuget push ./artifacts/Dialogative.*.nupkg --source "https://nuget.pkg.github.com/ydinkov/index.json" --api-key ${{ secrets.GH_PACKAGES_TOKEN }} --skip-duplicate

    - name: NuGet login (Trusted Publishing)
      if: github.event_name == 'push'
      id: nuget_login
      uses: NuGet/login@v1
      with:
        user: ${{ secrets.NUGET_USER }}


    - name: Push to Nuget
      if: github.event_name == 'push'
      run: dotnet nuget push ./artifacts/Dialogative.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ steps.nuget_login.outputs.NUGET_API_KEY }} --skip-duplicate
